export enum UserRole {
  BUYER = 'BUYER',
  SELLER = 'SELLER',
  ADMIN = 'ADMIN',
  SUPPORT = 'SUPPORT'
}

export enum OrderStatus {
  CREATED = 'CREATED',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  PAID = 'PAID',
  DELIVERED = 'DELIVERED',
  WAITING_BUYER_CONFIRMATION = 'WAITING_BUYER_CONFIRMATION',
  DISPUTED = 'DISPUTED',
  ESCALATED = 'ESCALATED',
  COMPLETED = 'COMPLETED',
  REFUNDED = 'REFUNDED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED'
}

export enum TransactionType {
  DEPOSIT = 'DEPOSIT',
  WITHDRAWAL = 'WITHDRAWAL',
  PURCHASE = 'PURCHASE',
  SALE = 'SALE',
  REFUND = 'REFUND',
  FEE = 'FEE',
  ESCROW_HOLD = 'ESCROW_HOLD',
  ESCROW_RELEASE = 'ESCROW_RELEASE',
  ESCROW_REFUND = 'ESCROW_REFUND',
  ADJUSTMENT = 'ADJUSTMENT'
}

export enum LedgerEntryStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  REFUNDED = 'REFUNDED',
  FROZEN = 'FROZEN',
  CANCELLED = 'CANCELLED'
}

export enum WalletTransactionStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED'
}

export enum DisputeStatus {
  OPEN = 'OPEN',
  AWAITING_SELLER = 'AWAITING_SELLER',
  AWAITING_BUYER = 'AWAITING_BUYER',
  ESCALATED = 'ESCALATED',
  RESOLVED_BUYER = 'RESOLVED_BUYER',
  RESOLVED_SELLER = 'RESOLVED_SELLER',
  CLOSED = 'CLOSED'
}

export enum DeliveryType {
  INSTANT = 'INSTANT',
  MANUAL = 'MANUAL'
}

export enum ProductStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  PENDING_REVIEW = 'PENDING_REVIEW',
  REJECTED = 'REJECTED',
  SOLD_OUT = 'SOLD_OUT'
}

export enum SellerStatus {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  REJECTED = 'REJECTED'
}

export enum WithdrawalStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED'
}

export enum DepositStatus {
  WAITING = 'WAITING',
  CONFIRMING = 'CONFIRMING',
  CONFIRMED = 'CONFIRMED',
  FAILED = 'FAILED',
  EXPIRED = 'EXPIRED'
}

export enum NotificationType {
  ORDER_NEW = 'ORDER_NEW',
  ORDER_UPDATE = 'ORDER_UPDATE',
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  WITHDRAWAL_PROCESSED = 'WITHDRAWAL_PROCESSED',
  DISPUTE_OPENED = 'DISPUTE_OPENED',
  DISPUTE_UPDATE = 'DISPUTE_UPDATE',
  MESSAGE_NEW = 'MESSAGE_NEW',
  REVIEW_RECEIVED = 'REVIEW_RECEIVED',
  SECURITY_ALERT = 'SECURITY_ALERT',
  VERIFICATION = 'VERIFICATION',
  SELLER_APPROVED = 'SELLER_APPROVED',
  PRODUCT_STATUS = 'PRODUCT_STATUS'
}

export enum ReportType {
  PRODUCT = 'PRODUCT',
  SELLER = 'SELLER',
  BUYER = 'BUYER',
  FRAUD = 'FRAUD',
  MESSAGE = 'MESSAGE'
}

export enum RiskLevel {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL'
}
