/**
 * Payment methods available to the Auto-P2P flow.
 *
 * The database still stores this value in P2POffer.giftCardType for backwards
 * compatibility with existing offers and gift-card assets.
 */
export const AUTO_P2P_PAYMENT_METHODS = [
  'Vodafone Cash', 'InstaPay', 'STC Pay', 'Urpay', 'Zain Cash', 'AsiaHawala', 'CliQ',
  'Orange Cash', 'Etisalat Cash', 'Telda', 'Baridimob', 'CIH Bank', 'Attijariwafa Bank',
  'JEEP Wallet', 'OMT', 'Western Union', 'MoneyGram', 'Wise', 'Revolut', 'Payoneer',
  'Skrill', 'Neteller', 'PayPal', 'Zelle', 'Cash App', 'Venmo', 'ACH Transfer',
  'SEPA Instant', 'SEPA Credit Transfer', 'Faster Payments', 'Monzo', 'Bunq', 'N26',
  'Bank Transfer', 'Wire Transfer', 'Visa', 'Mastercard', 'UPI', 'IMPS', 'NEFT', 'RTGS',
  'Paytm', 'PhonePe', 'Google Pay', 'Apple Pay', 'GCash', 'Maya', 'BDO Bank', 'BPI Bank',
  'Dana', 'OVO', 'ShopeePay', 'MoMo', 'BCA Bank', 'Maybank', 'EasyPaisa', 'JazzCash',
  'NayaPay', 'Meezan Bank', 'HBL Bank', 'PIX', 'Mercado Pago', 'Bancolombia', 'SPEI',
  'M-Pesa', 'MTN Mobile Money', 'Airtel Money', 'Kuda', 'OPay', 'Palmpay', 'GTBank',
  'QIWI', 'WebMoney', 'Yandex Money', 'Tinkoff Bank', 'Sberbank', 'ADVcash', 'Payeer',
  'Perfect Money', 'AirTM', 'Chime', 'Ally Bank', 'Capital One', 'Chase', 'Bank of America',
  'Wells Fargo', 'BBVA', 'Santander', 'HSBC', 'BNP Paribas', 'Société Générale',
  'Deutsche Bank', 'Commerzbank', 'Intesa Sanpaolo', 'UniCredit', 'UBS', 'Credit Suisse',
  'Barclays', 'Lloyds', 'RBS', 'KakaoPay', 'Toss', 'LINE Pay', 'AliPay', 'WeChat Pay',
  'PromptPay', 'TrueMoney', 'GoPay', 'LinkAja', 'Boost', "Touch 'n Go", 'GrabPay',
  'Kakao Bank', 'K-Bank', 'Shinhan Bank', 'Hana Bank', 'Commonwealth Bank', 'ANZ',
  'Westpac', 'NAB', 'Scotiabank', 'RBC', 'TD Bank', 'BMO', 'CIBC', 'Itau', 'Bradesco',
  'Caixa', 'Banco do Brasil', 'Banco Galicia', 'Banco Macro', 'Naranja X', 'Davivienda',
  'Nequi', 'Daviplata', 'BCP', 'Interbank', 'BBVA Bancomer', 'Banorte', 'Banamex', 'OXXO',
  'Orange Money', 'Wave', 'Vodafone M-Pesa', 'EcoCash', 'Telebirr', 'CBE Birr', 'E-Dinar',
  'BMCE Bank', 'Crédit Agricole', 'Attijari Bank', 'Banque de Tunisie', 'Bank of Alexandria',
  'Banque Misr', 'National Bank of Egypt', 'Commercial International Bank', 'QNB',
  'Arab Bank', 'Housing Bank', 'Zain Cash Jordan', 'Umniah Wallet', 'Orange Money Jordan',
  'Rafidain Bank', 'Rasheed Bank', 'Trade Bank of Iraq', 'FIB', 'Al Rajhi Bank', 'SNB',
  'Riyad Bank', 'Alinma Bank', 'Bank AlBilad', 'SAB', 'Dubai Islamic Bank', 'ADCB', 'FAB',
  'ENBD', 'Mashreq Neo', 'Bank Dhofar', 'Bank Muscat', 'Bank Sohar', 'NBO',
  'National Bank of Kuwait', 'KFH', 'Boubyan Bank', 'NBK', 'Gulf Bank', 'QNB Qatar',
  'Commercial Bank of Qatar', 'Doha Bank', 'Masraf Al Rayan', 'Bank Alfalah', 'Allied Bank',
  'Askari Bank', 'Bank AL Habib', 'MCB', 'UBL', 'Bkash', 'Nagad', 'Rocket', 'Cellfin',
  'Brac Bank', 'City Bank', 'Islami Bank', 'Commercial Bank of Ceylon', 'Sampath Bank',
  'HNB', 'BOC', 'CB Bank', 'KBZ Bank', 'Aya Bank', 'Wave Money', 'ABA Bank', 'Acleda Bank',
  'Wing Bank', 'Canadia Bank', 'Vietcombank', 'Techcombank', 'BIDV', 'VietinBank',
  'MB Bank', 'Momo Wallet', 'ZaloPay', 'Viettel Money', 'ShopeePay Vietnam',
  'Krungthai Bank', 'Kasikornbank', 'Siam Commercial Bank', 'Bangkok Bank', 'CIMB Bank',
  'Public Bank', 'Hong Leong Bank', 'AmBank', 'BDO Unibank', 'Metrobank', 'Land Bank',
  'Security Bank', 'ASB Bank', 'Bank of New Zealand', 'Westpac NZ', 'DBS Bank', 'OCBC Bank',
  'UOB Bank', 'POSB', 'Standard Chartered', 'Citibank', 'ICBC', 'China Construction Bank',
  'Agricultural Bank of China', 'Bank of China', 'Bank of Communications',
  'Postal Savings Bank of China', 'China Merchants Bank', 'Industrial Bank',
  'Shanghai Pudong Development Bank', 'China CITIC Bank', 'American Express', 'Discover',
  'Diners Club', 'JCB', 'UnionPay', 'Maestro', 'eftpos', 'Interac', 'Cartes Bancaires',
  'Bacs', 'AU BECS', 'NZ BECS', 'iDEAL', 'Bancontact', 'FPX', 'PayNow', 'Swish', 'PayTo',
  'Blik', 'Twint', 'Trustly', 'Knet', 'Sadad', 'Bit', 'Pepper Pay', 'Samsung Pay',
  'Boleto', 'Elo', 'Klarna', 'Afterpay', 'Clearpay', 'Affirm', 'Zip', 'Multibanco',
  'Konbini', 'Safaricom', 'Tigo Pesa', 'Halopesa', 'Airtel Money Kenya', 'ECOCASH Zimbabwe',
  'Mukuru', 'InnBucks', 'EcoBank', 'Access Bank', 'Zenith Bank', 'UBA', 'First Bank',
  'Fidelity Bank', 'Stanbic IBTC', 'Sterling Bank', 'Wema Bank', 'Polaris Bank',
  'Keystone Bank', 'VFD Bank', 'Carbon', 'FairMoney', 'Moniepoint', 'PiggyVest',
  'Kudabank', 'Gomoney', 'Rubies Bank', 'Sparkle', 'Mintyn', 'VBank', 'ALAT', 'Dot Bank',
  'Branch', 'Renmoney', 'Specta', 'Page Financials', 'CreditDirect', 'QuickCheck', 'Umba',
  'Stripe', 'Square', 'Adyen', 'Solidgate', 'Worldpay', 'Checkout.com', 'Braintree',
  'Authorize.Net', '2Checkout', 'Verifone', 'PayU', 'Ingenico', 'CyberSource', 'First Data',
  'Chase Paymentech', 'Elavon', 'Global Payments', 'TSYS', 'Heartland', 'Worldline', 'Nexi',
  'Nets', 'Barclaycard', 'Sofort', 'Giropay', 'EPS', 'Przelewy24', 'Payconiq', 'MB Way',
  'Bizum', 'Satispay', 'Bancomat Pay', 'Postepay', 'Hype', 'Fineco Bank', 'Airwallex',
  'Instarem', 'Nium', 'Aspire', 'Spenmo', 'Volopay', 'YouTrip', 'BigPay', 'MatchMove',
  'Razer Pay', 'Setel', 'JomPAY', 'DuitNow', 'DuitNow QR', 'DuitNow Transfer',
  'DuitNow AutoDebit', 'ShopBack', 'Dash', 'FavePay', 'NetsPay', 'Paylah by DBS',
  'BharatPe', 'Pine Labs', 'Razorpay', 'Cashfree', 'PayU India', 'BillDesk', 'CCAvenue',
  'Instamojo', 'RazorpayX', 'Juspay', 'Open.fi', 'Fi Money', 'Jupiter Money', 'Niyo',
  'Freo', 'Slice', 'Uni Card', 'OneCard', 'LazyPay', 'Simpl', 'ZestMoney', 'Amazon Pay',
  'Mobikwik', 'Freecharge', 'Ola Money', 'JioMoney', 'Airtel Payments Bank',
  'India Post Payments Bank', 'Fino Payments Bank', 'RuPay', 'BharatQR', 'Aadhaar Pay',
  'AEPS', 'NACH', 'eNACH', 'UPI Lite', 'UPI 123Pay', 'PhonePe Business',
  'Google Pay Business', 'Amazon Pay Business', 'Paytm Business', 'PayPal Business',
  'Skrill Wallet', 'Neteller Wallet', 'Zelle Business', 'Cash App Business', 'Venmo Business',
  'Monzo Business', 'Revolut Business', 'Wise Business', 'Payoneer Account',
  'Stripe Checkout', 'Square POS', 'Adyen Payments', 'Klarna Checkout', 'iDEAL Payment',
  'Bancontact App', 'Multibanco Portal', 'MB Way App', 'Bizum App', 'PostFinance',
  'Raiffeisen Switzerland', 'Caisse d’Epargne', 'Banque Populaire', 'Crédit Mutuel',
  'La Banque Postale', 'Boursorama Banque', 'Hello bank App', 'Nickel Account',
  'Greenlight Card', 'Current Banking', 'GoHenry App', 'Airwallex Platform',
  'Touch n Go eWallet', 'Boost Wallet', 'MAE App', 'CIMB Clicks MY', 'HLB Connect MY',
  'RHB Now MY', 'AmOnline MY', 'UOB Mighty MY', 'JomPAY Portal', 'FPX Merchant',
  'DuitNow QR Code', 'GrabMerchant App', 'PayHalal Gateway', 'GrabPay SG', 'Dash Wallet',
  'FavePay App', 'HDFC Mobile', 'ICICI iMobile', 'Axis Mobile', 'Kotak Mobile',
  'Jio Payments App', 'Paytm Payments App', 'IPPB Mobile App', 'FinoPay App',
  'Paga', 'Pocket App', 'PiggyVest Savings', 'Cowrywise', 'Moniepoint Business',
  'OPay Wallet', 'PalmPay Web', 'Kuda Business', 'Carbon Business', 'FairMoney Business',
  'Branch Business', 'Umba Business', 'Stripe Checkout', 'PayPal Web', 'Skrill Web',
  'Neteller Web', 'Zelle Web', 'Cash App Web', 'Venmo Web', 'Monzo Web', 'Revolut Web',
  'Wise Web', 'Payoneer Web', 'Kuda Web', 'Carbon Web', 'FairMoney Web', 'PalmPay Web',
  'Moniepoint Web', 'OPay Web', 'Branch Web', 'Umba Web', 'Renmoney Web', 'Specta Web',
  'QuickCheck Web', 'VBank Web', 'ALAT Web', 'Mintyn Web', 'Dot Bank Web', 'Kuda Business Web',
  'Monzo Business', 'Revolut Business', 'Wise Business', 'Payoneer Account',
  'PayPal Business', 'Solidgate API', 'Worldpay Gateway', 'Checkout.com Hub',
  'Braintree Dashboard', 'Authorize.Net Merchant', 'Verifone POS', 'PayU Latam',
  'Ingenico Terminal', 'CyberSource API', 'First Data POS', 'Elavon Merchant',
  'Global Payments Core', 'TSYS Processing', 'Heartland POS', 'Worldline Terminal',
  'Nexi Pay', 'Nets Merchant', 'Barclaycard Business', 'Sofort Banking', 'Giropay Online',
  'EPS Transfer', 'Przelewy24 Online', 'Bancontact Mobile', 'Multibanco Entidade',
  'Postepay App', 'Sella Banking', 'Buddybank App', 'Illimity Bank', 'Widiba Bank',
  'Fineco App', 'CheBanca App', 'Mediolanum App', 'Generali App', 'Allianz Wallet',
  'Zurich App', 'AXA App', 'Aviva Portal', 'Prudential Wallet', 'Fidelity Portal',
  'BlackRock App', 'Vanguard App', 'PostFinance App', 'Raiffeisen Mobile',
  'Esprit App', 'Orange Bank App', 'Ma French Bank App', 'Pixpay App', 'Kard App',
  'Vybe App', 'Step Mobile', 'Copper Banking', 'RoosterMoney App', 'Osper Card',
  'Nimbl Card', 'Spriggy Card', 'Kit App', 'Square Peg Portal', 'Currenxie Account',
  'Statrys Account', 'Neat Business', 'TranSwap Platform', 'Wallex Platform',
  'Instarem App', 'Nium Platform', 'Aspire Business', 'Spenmo Card', 'Volopay Card',
  'YouTrip App', 'BigPay App', 'MatchMove Wallet', 'GrabPay MY', 'Setel App',
  'MAE by Maybank247', 'CIMB Clicks MY', 'HLB Connect MY', 'RHB Now MY', 'PBe Bank MY',
  'Standard Chartered Mobile', 'HSBC Malaysia', 'Bank Islam', 'Bank Muamalat',
  'Alliance Bank', 'Affin Bank', 'Agrobank', 'Bank Rakyat', 'BSN', 'KFH Malaysia',
  'Al Rajhi Malaysia', 'MBSB Bank', 'Co-op Bank Pertama', 'Boost Biz', 'GrabMerchant',
  'Touch n Go Merchant', 'Razer Merchant', 'KiplePay', 'Bayo', 'ManagePay', 'Revenue Monster',
  'Fave', 'GrabPay Singapore', 'Kris+ by Singapore Airlines', 'OCBC Pay Anyone',
  'UOB TMRW', 'Standard Chartered Pay', 'HSBC Singapore', 'Citibank Singapore',
  'Maybank Singapore', 'RHB Singapore', 'CIMB Singapore', 'State Bank of India Singapore',
  'Indian Overseas Bank', 'Indian Bank', 'UCO Bank', 'Bank of Baroda', 'Punjab National Bank',
  'Canara Bank', 'Union Bank of India', 'HDFC Bank', 'ICICI Bank', 'Axis Bank',
  'Kotak Mahindra Bank', 'IndusInd Bank', 'Federal Bank', 'IDBI Bank', 'Yes Bank',
  'RBL Bank', 'Bandhan Bank', 'IDFC First Bank', 'South Indian Bank', 'Karur Vysya Bank',
  'Karnataka Bank', 'Jammu & Kashmir Bank', 'Tamilnad Mercantile Bank', 'Catholic Syrian Bank',
  'Dhanlaxmi Bank', 'DCB Bank', 'City Union Bank', 'Nainital Bank', 'Maharashtra Bank',
  'Central Bank of India', 'Punjab & Sind Bank', 'Bank of Maharashtra', 'Ujjivan',
  'Janalakshmi', 'Equitas', 'AU Small Finance', 'Capital Small Finance', 'Suryoday',
  'Utkarsh', 'ESAF', 'Fincare', 'North East Small Finance', 'Shivalik', 'JioMoney',
  'Mobikwik', 'Freecharge', 'Ola Money', 'Oxigen', 'Sahaj', 'Spice Money', 'Vakrangee',
  'CSC', 'PayPoint', 'Suvidhaa', 'E-Mitra', 'Mahaonline', 'MeeSeva', 'AP Online',
  'TS Online', 'MP Online', 'CSC SPV', 'Digital Seva', 'Apna CSC', 'Sahaj eVillage',
  'Common Service Centre', 'Digital India', 'UMANG', 'DigiLocker', 'mAadhaar',
  'mParivahan', 'IRCTC', 'Bharat BillPay', 'NPCI', 'IMPS Native', 'NEFT Native',
  'RTGS Native', 'ECS', 'CTS', 'NFS', 'IMPS P2P', 'IMPS P2A', 'IMPS P2U', 'UPI P2P',
  'UPI P2M', 'UPI P2B', 'UPI B2B', 'UPI Cross Border', 'UPI International', 'Pine Labs',
  'Mswipe', 'Paytm Payment Gateway', 'Cashfree Payments', 'Zaakpay', 'Atom Technologies',
  'EBS', 'DirecPay', 'Paymate', 'Safexpay', 'PayGlocal', 'Jupiter Money', 'Postpe India',
  'Simpl', 'ePayLater', 'Paytm Postpaid', 'Amazon Pay Later', 'Flipkart Pay Later',
  'Bob World', 'YONO SBI', 'iMobile', 'Kotak 811', 'FedMobile', 'IndOASIS', 'PNB ONE',
  'canara ai1', 'Jio Payments Bank', 'Airtel Payments Bank', 'Paytm Payments Bank',
  'NSDL Payments Bank', 'M-Pesa Kenya', 'Tigo Pesa Tanzania', 'MTN MoMo Uganda',
  'Airtel Money Zambia', 'Orange Money Senegal', 'Moov Money', "Wave Cote d'Ivoire",
  'Telebirr Ethiopia', 'Sayer', 'e-Dinar Tunisie', 'CCP Algeria', 'BaridiMob App',
  'Attijari Mobile', 'CIH Mobile', 'BMCE Direct', 'Pocket Bank', 'Chaabi Net',
  'Banque Populaire Mobile', 'Win by INWI', 'e-salam Bank', 'Banxy', 'MyBk', 'BDLnet',
  'BEA direct', 'CPA online', 'BADR connect', 'BNA', 'BNI', 'Ecobank Mobile', 'UBA Omni',
  'AccessMore', 'Zenith Mobile', 'FirstMobile', 'GTWorld', 'ALAT by Wema',
  'Kuda Microfinance', 'V by VFD', 'Carbon Loan', 'FairMoney App', 'PalmPay Agent',
  'Moniepoint Business', 'Paga', 'Pocket App', 'PiggyVest Savings', 'Cowrywise',
  'Branch Wallet', 'Renmoney Loans', 'Specta Credit', 'QuickCheck App', 'Umba Digital',
  'Kudabank App', 'Gomoney Wallet', 'Rubies Digital', 'Sparkle Business', 'Mintyn Digital',
  'Dot Bank App', 'Branch Business', 'Umba Business', 'FairMoney Web App', 'PalmPay Web App',
  'Moniepoint Web App', 'OPay Web App', 'Kuda Business App', 'Aviva Investors Portal',
  'Julius Baer Mobile', 'Post Holder Portal', 'Post Office App', 'Post Remittance App',
  'Empire Trust Microfinance', 'Fina Trust Microfinance', 'Fortis Microfinance',
  'Hasal Microfinance', 'Infinity Microfinance', 'NPF Microfinance', 'Ohha Microfinance',
  'TC Microfinance', 'Wetland Microfinance', 'Bosak Microfinance', 'Seedvest Microfinance',
  'Regent Microfinance', 'Fullrange Microfinance', 'Daylight Microfinance', 'Fast Credit',
  'Page International', 'Rosabon Financial', 'Creditville', 'Sovereign Trust',
  'Veritas Kapital', 'Linkage Assurance', 'AIICO Insurance', 'AXA Mansard', 'Leadway Assurance',
  'Custodian Investment', 'Mutual Benefits Assurance', 'Corner Stone Insurance',
  'Lasaco Assurance', 'Nem Insurance', 'Niger Insurance', 'Prestige Assurance',
  'Sovereign Trust Insurance', 'Universal Insurance', 'Goldlink Insurance',
  'International Energy Insurance', 'Staco Insurance', 'Standard Alliance', 'Guinea Insurance',
  'African Alliance', 'Capital Express', 'Great Nigeria Insurance',
  'Industrial and General Insurance', 'Royal Exchange', 'Anchor Insurance',
  'Consolidated Hallmark'
] as const;

export type AutoP2PPaymentMethod = (typeof AUTO_P2P_PAYMENT_METHODS)[number];
